---
# file: roles/grid-engine/tasks/main.yml
- name: SGE | Install gridengine-client
  apt: pkg=gridengine-client state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-qmon
  apt: pkg=gridengine-qmon state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-exec
  apt: pkg=gridengine-exec state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-master 
  apt: pkg=gridengine-master state=present update_cache=yes cache_valid_time=3600
  when: grid_engine_master == True
