#!/usr/bin/env bash
set -e

#install perl modules
sudo apt-get update
apt-get install libjson-perl libtemplate-perl libconfig-simple-perl libcarp-always-perl libipc-system-simple-perl make gcc libgetopt-euclid-perl 

#install Vagrant
wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb
sudo dpkg -i vagrant_1.6.3_x86_64.deb

#install Vagrant plugin

## uncomment one for your platform
# vagrant plugin install vagrant-aws
# vagrant plugin install vagrant-openstack-plugin --plugin-version 0.7.0
# vagrant plugin install vagrant-vcloud --plugin-version 0.4.3


#Install Ansible
sudo apt-get install python-crypto python-jinja2 python-markupsafe sshpass python-crypto-dbg python-crypto-doc python-jinja2-doc python-jinja2 python-markupsafe sshpass python-crypto python-setuptools

wget https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-dependencies/ansible/ansible/1.6.10-precise/ansible-1.6.10-precise.deb
sudo dpkg --install ansible-1.6.10-precise.deb

