#!/usr/bin/env bash
set -e 

#install dependencies
sudo apt-get install make gcc python-crypto python-jinja2 python-markupsafe sshpass python-crypto-dbg python-crypto-doc python-jinja2-doc python-jinja2 python-markupsafe sshpass python-crypto python-setuptools

#download ansible package
wget https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-dependencies/ansible/ansible/1.6.10-precise/ansible-1.6.10-precise.deb

#install ansible
sudo dpkg --install ansible-1.6.10-precise.deb
