---
# CaPSID pipeline
- name: CaPSID pipeline | Install development tools
  apt: pkg=build-essential state=present update_cache=yes cache_valid_time=3600

- name: CaPSID pipeline | Install python
  apt: pkg=python2.7 state=present update_cache=yes cache_valid_time=3600
  apt: pkg=python2.7-dev state=present update_cache=yes cache_valid_time=3600

- name: CaPSID pipeline | Get pip
  get_url:
    dest: '/tmp/get-pip.py'
    url: 'https://raw.github.com/pypa/pip/master/contrib/get-pip.py'

- name: CaPSID pipeline | Install pip
  shell: python2.7 /tmp/get-pip.py creates=/usr/local/bin/pip

- name: CaPSID pipeline | Install git
  apt: pkg=git state=present update_cache=yes cache_valid_time=3600

- name: CaPSID pipeline | Create /var/local
  shell: mkdir -p /var/local creates=/var/local

- name: CaPSID pipeline | Check out CaPSID from Github
  git:
    repo: https://github.com/capsid/capsid-pipeline.git
    dest: /var/local/capsid_pipeline
    update: yes
    version: develop

# OF course, if we had dependencies that were Debian packaged and suitable, then
# that would be better to reduce C compilation time. 

- name: CaPSID pipeline | Install CaPSID dependencies
  shell: pip install -e . chdir=/var/local/capsid_pipeline

# There is no good reason why we ought to need to do this, but we might. Anyway,
# here we go. 

- name: CaPSID pipeline | Install CaPSID
  shell: python setup.py install chdir=/var/local/capsid_pipeline

# Add in R

- include: r.yml

# Add in the aligners. We install all of them on all systems, just in case, as it
# isn't too much work. 

- include: aligners.yml
