- name: CaPSID pipeline | Get SHRiMP2
  get_url:
    dest: '/tmp/SHRiMP_2_2_3.lx26.x86_64.tar.gz'
    url: 'http://compbio.cs.toronto.edu/shrimp/releases/SHRiMP_2_2_3.lx26.x86_64.tar.gz'

- name: CaPSID pipeline | Unpack SHRiMP2
  shell: unzip /tmp/SHRiMP_2_2_3.lx26.x86_64.tar.gz chdir=/var/local creates=/var/local/SHRiMP_2_2_3

- name: CaPSID pipeline | Make clean link to SHRiMP2
  file: state=link src=/var/local/SHRiMP_2_2_3 dest=/var/local/SHRiMP
