---
# file: roles/seqware-code/tasks/main.yml

- name:  Set up SeqWare working directories
  file: path={{ item.path }} state={{ item.state }} owner={{ item.owner }} recurse={{ item.recurse }} mode={{ item.mode}} group={{ item.group }}
  with_items:
     - { state: 'directory', path: '~seqware/bin', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/jars', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/crons', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/logs', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/released-bundles', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/workflow-dev', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/.seqware/self-installs', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     - { state: 'directory', path: '~seqware/gitroot/seqware', owner: 'seqware', group: 'seqware', recurse: 'yes', mode: '0700' }
     
  #hmmm, no module for hadoop file operations
- name:  Setup HDFS User Directories
  sudo: yes
  sudo_user: hdfs
  command: $item
  ignore_errors: yes
  with_items: 
    - hadoop fs -mkdir -p /user/seqware
    - hadoop fs -chown -R seqware /user/seqware
    
- name:  Template seqware settings
  template: src=settings.j2 dest=~seqware/.seqware/settings mode=0640
  
# I'm still checking out since I will need the SQL schema file for example
- name: SeqWare - Code - Git | Cloning seqware
  git: repo=https://github.com/SeqWare/seqware.git dest=~seqware/gitroot/seqware

# setup bash profile for seqware
- name:  Bash profile
  lineinfile: 
    dest: ~seqware/.bash_profile
    create: yes
    line: 'export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"'
    state: present
    insertafter: EOF
    
- name:  Make everything owned by seqware
  file: path=~seqware state=directory owner=seqware group=seqware recurse=yes

- include: 'git.yml'
  when: seqware_provider == "git"

- include: 'artifactory.yml'
  when: seqware_provider == "artifactory"

- name:  Make everything owned by seqware
  file: path=~seqware state=directory owner=seqware group=seqware recurse=yes