---
# file: roles/seqware-integration-tests/tasks/git.yml
  
- name: Ensure Glassfish database location is correct
  lineinfile: 
    dest: ~seqware/gitroot/seqware/pom.xml
    regexp: '<seqware_meta_db_name>test_seqware_meta_db</seqware_meta_db_name>' 
    line: '<seqware_meta_db_name>seqware_meta_db</seqware_meta_db_name>' 
    state: present
    
  # this sucks because it doesn't look like the shell command picks up the MAVEN_OPTS that we've already defined in the login shell
- name: Run integration tests and build a log
  sudo: yes
  sudo_user: seqware
  shell: chdir=~seqware/gitroot/seqware creates=~seqware/gitroot/seqware/it.log export MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=1024m" && {{ seqware_it_cmd }} 2>&1 | tee it.log


