# HTTP
http:
  rootPath: "/api/*"
  port: %{DCC_PORTAL_PORT}

# ElasticSearch index and hosts
elastic:
  indexName: "%{DCC_INDEX_NAME}"

# FIXME: need to prepare this section and include as a var
  nodeAddresses:
%{DCC_PORTAL_SETTINGS_HOST_STR}

# Genomemaps
browser:
  dataSources:
     - uri: gene
       className: org.icgc.dcc.portal.browser.ds.GeneDataSource
     - uri: mutation
       className: org.icgc.dcc.portal.browser.ds.MutationDataSource

# Data download
download:
  enabled: true
  uri: "%{DCC_PORTAL_DOWNLOADER_URI}"
  dynamicRootPath: "%{DCC_PORTAL_DOWNLOADER_DYNAMIC_PATH}"
  staticRootPath: "%{DCC_PORTAL_DOWNLOADER_STATIC_PATH}"
  currentReleaseSymlink: "%{DCC_PORTAL_DOWNLOADER_CURRENT_PATH}"
  maxUsers: %{DCC_PORTAL_DOWNLOADER_MAX_USERS}
  stage: "DEVELOPMENT"

# Logging settings
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  level: INFO

  # Logger-specific levels
  loggers:

    # Very chatty
    "com.wordnik.swagger.jsonschema.ApiModelParser": WARN

    # ERRORs should be converted to WARNs in Swagger 1.2.2
    "com.wordnik.swagger.jaxrs.HelpApi": OFF

