# HTTP
http:
  rootPath: "/api/*"
  port: %{DCC_PORTAL_PORT}

# ElasticSearch index and hosts
elastic:
  indexName: "%{DCC_INDEX_NAME}"

# FIXME: need to prepare this section and include as a var
  nodeAddresses:
        - host: "master"
        - port: 9300

# Genomemaps
browser:
  dataSources:
     - uri: gene
       className: org.icgc.dcc.portal.browser.ds.GeneDataSource
     - uri: mutation
       className: org.icgc.dcc.portal.browser.ds.MutationDataSource

# Data download
download:
  enabled: true
  uri: "hdfs://master:8020"
  staticRootPath: "/icgc/download/static"
  dynamicRootPath: "/icgc/download/dynamic"
  currentReleaseSymlink: "/current /TRA"
  stage: "PRODUCTION"
  quorum: "master"
  oozieUrl: "http://master:11000/oozie"
  appPath: "hdfs://master:8020/user/downloader/workflows/archive-main"
  releaseName: "TRA"

# Logging settings
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  level: INFO

  # Logger-specific levels
  loggers:

    # Very chatty
    "com.wordnik.swagger.jsonschema.ApiModelParser": WARN

    # ERRORs should be converted to WARNs in Swagger 1.2.2
    "com.wordnik.swagger.jaxrs.HelpApi": OFF

