---

- name: Install Bindle dependencies
  apt: name= {{ item }} state=latest update_cache=yes
  with_items:
    - git 
    - gcc
    - make
    - python-crypto 
    - python-jinja2 
    - python-markupsafe 
    - sshpass 
    - python-crypto-dbg 
    - python-crypto-doc 
    - python-jinja2-doc 
    - python-markupsafe 
    - python-setuptools

- name: Download Ansible 1.6 deb package
  get_url: 
    dest=/tmp
    url=https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-dependencies/ansible/ansible/1.6.10-precise/ansible-1.6.10-precise.deb
    mode=755

- name: Install Ansible 1.6
  apt: deb=/tmp/ansible-1.6.10-precise.deb

- name: Download Vagrant deb package
  get_url: 
    dest=/tmp
    url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb
    mode=755
  
- name: Install Vagrant deb package
  apt: deb=/tmp/vagrant_1.6.3_x86_64.deb

- name: Install Vagrant providers
  command: vagrant plugin install {{ vagrant_plugin }} --plugin-version {{ vagrant_plugin_version }}

# vagrant plugin install vagrant-openstack-plugin --plugin-version 0.7.0
# vagrant plugin install vagrant-vcloud --plugin-version 0.4.3

- name: Install Perl dependencies
  apt: name= {{ item }} state=latest update_cache=yes
  with_items:
	- libgetopt-euclid-perl
	- libjson-perl
	- libtemplate-perl
	- libconfig-simple-perl
	- libcarp-always-perl
	- libipc-system-simple-perl

- name: Create .bindle directory
  file: path=~/.bindle state=directory

- name: Copy the template config from Github into the ~/.bindle directory
  copy: src=/root/architecture2/Bindle/template/config/{{ item }}  dest=~/.bindle/
  with_items: {{ bindle_config }}
