#!/bin/bash

# This script is used to ensure the proper configuration of an AWS instance
# with a dynamic IP and ephemeral disks. Install as follows:
# 
# sudo cp hadoop-init-worker /etc/init.d/hadoop-init
# sudo chown root:root /etc/init.d/hadoop-init
# sudo chmod 755 /etc/init.d/hadoop-init
# sudo sysv-rc-conf hadoop-init on


echo `date` 'Begin initializing hadoop filesystems' >> /tmp/hadoop-init.log

HOST='%{HOST}'

# remove the old 'master' entry
cat /etc/hosts | grep -v $HOST > /tmp/hosts

# add a new 'master' entry using the current IP
echo `/sbin/ifconfig  | grep -A 3 eth0 | grep 'inet addr' | perl -e 'while(<>){ chomp; /inet addr:(\d+\.\d+\.\d+\.\d+)/; print $1; }'` $HOST >> /tmp/hosts

cp /tmp/hosts /etc/hosts

# shutdown hadoop services
service hbase-regionserver stop
service hadoop-0.20-mapreduce-tasktracker stop
service hadoop-hdfs-datanode stop

stat /data/1/
if [ $? != 0 ]; then

# initialize ephemeral disk for hadoop
mkdir -p /data/1/dfs/dn
chown -R hdfs:hdfs /data/1/dfs/dn
chmod 700 /data/1/dfs/dn
mkdir -p /data/1/mapred/local
chown -R mapred:mapred /data/1/mapred
mkdir -p /tmp/hadoop-mapred
chown mapred:mapred /tmp/hadoop-mapred
chmod -R a+rwx /tmp/hadoop-mapred

# initialize HDFS
service hadoop-hdfs-datanode start

fi

# initialize HDFS for services
sudo -u hdfs hadoop fs -mkdir /tmp
sudo -u hdfs hadoop fs -chmod -R 1777 /tmp
sudo -u hdfs hadoop fs -mkdir -p /var/lib/hadoop-hdfs/cache/mapred/mapred/staging
sudo -u hdfs hadoop fs -chmod 1777 /var/lib/hadoop-hdfs/cache/mapred/mapred/staging
sudo -u hdfs hadoop fs -chown -R mapred /var/lib/hadoop-hdfs/cache/mapred
sudo -u hdfs hadoop fs -mkdir /tmp/mapred/system
sudo -u hdfs hadoop fs -chown mapred:hadoop /tmp/mapred/system
sudo -u hdfs hadoop fs -mkdir -p /tmp/hadoop-mapred/mapred
sudo -u hdfs hadoop fs -chmod -R a+wrx /tmp/hadoop-mapred/mapred
sudo -u hdfs hadoop fs -mkdir /hbase
sudo -u hdfs hadoop fs -chown hbase /hbase

# initialize HDFS for seqware
sudo -u hdfs hadoop fs -mkdir -p /user/seqware
sudo -u hdfs hadoop fs -chown -R seqware /user/seqware

# start hadoop services
service hadoop-0.20-mapreduce-tasktracker start
service hbase-regionserver start

echo `date` 'Completed initializing hadoop filesystems' >> /tmp/hadoop-init.log

