#!/bin/bash

# This script is used to ensure the proper configuration of an AWS instance
# with a dynamic IP and ephemeral disks. Install as follows:
# 
# sudo cp hadoop-init-master /etc/init.d/hadoop-init
# sudo chown root:root /etc/init.d/hadoop-init
# sudo chmod 755 /etc/init.d/hadoop-init
# sudo sysv-rc-conf hadoop-init on


echo `date` 'Begin initializing sge' >> /tmp/sge-init.log

HOST='%{HOST}'

# remove the old 'master' entry
cat /etc/hosts | grep -v $HOST > /tmp/hosts

# add a new 'master' entry using the current IP
echo `/sbin/ifconfig  | grep -A 3 eth0 | grep 'inet addr' | perl -e 'while(<>){ chomp; /inet addr:(\d+\.\d+\.\d+\.\d+)/; print $1; }'` $HOST >> /tmp/hosts

cp /tmp/hosts /etc/hosts

# just call the initialization script that originally setup SGE
bash /vagrant_scripts/config_script.$HOST\_ubuntu_12.04_gridengine_script.sh

echo `date` 'Completed initializing sge' >> /tmp/sge-init.log

