--- 
# file: seqware-install.yml
# This file is used for installing a seqware cluster

# This play runs first, and gathers a complete set of properties for everything
- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

# Next, let's generate common files, such as the hosts file. This requires the
# previous setup to have been run in a separate play, it seemed
- hosts: all
  sudo: True
  roles:
    - role: common
    
# Not sure why, but I needed this to create a /etc/hosts that actually works with the Ubuntu image here on openstack
- hosts: all
  sudo: True
  # Idempotent way to build a /etc/hosts file with Ansible using your Ansible hosts inventory for a source.
  # Will include all hosts the playbook is run on.
  # Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
  tasks:
  - name: Build hosts file for all hosts
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: groups['all']

# The grid master depends on the hosts file, as we need to know at least who we
# are by this stage. 
- hosts: master 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: True }
    - { role: seqware-master }

- hosts: worker 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }
    - { role: grid-engine, grid_engine_master: False }
    - { role: seqware-worker }
