---
# file: roles/grid-engine/tasks/main.yml
- name: SGE | Install gridengine-client
  apt: pkg=gridengine-client state=present update_cache=yes cache_valid_time=3600
  
- name: SGE | Install gridengine-common
  apt: pkg=gridengine-common state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-qmon
  apt: pkg=gridengine-qmon state=present update_cache=yes cache_valid_time=3600
  when: grid_engine_master == True

- name: SGE | Install gridengine-exec
  apt: pkg=gridengine-exec state=present update_cache=yes cache_valid_time=3600

- name: SGE | Install gridengine-master 
  apt: pkg=gridengine-master state=present update_cache=yes cache_valid_time=3600
  when: grid_engine_master == True

- name: SGE | Configure master
  command: qconf -as {{ inventory_hostname }}
  when: grid_engine_master == True
  register: configure_master_as
  changed_when: not 'already exists' in configure_master_as.stderr

# Add the user on both master and worker nodes
- name: SGE | Create user capsid
  user: name=capsid comment="CaPSID worker" state=present
  
- name: SGE | Make a directory for our SGE templates
  file: state=directory path=/etc/gridengine/templates mode=0744
  when: grid_engine_master == True
  
# setup memory as a consumable resource
- name: SGE | Template memory configuration file
  template: src=sc.j2 dest=/etc/gridengine/templates/sge_sc
  register: memory_template
  when: grid_engine_master == True
  
- name: SGE | Setup memory as consumable resource
  command: qconf -Mc /etc/gridengine/templates/sge_sc
  when: grid_engine_master == True and memory_template.changed
  register: memory_consumable
  changed_when: not 'Complex attribute configuration has not been changed' in memory_consumable.stderr

# Be careful when adding the user. First get he current list, and only add if it isn't
# already present.
- name: SGE | Check current user list
  shell: qconf -su users | grep -E "^entries" | cut -f2 -d " "
  when: grid_engine_master == True
  register: sge_current_users
  changed_when: false

- name: SGE | Add the capsid user
  command: qconf -au capsid users
  when: grid_engine_master == True and not 'capsid' in sge_current_users.stdout.split(',')

# Again, we don't want to do this if it already exists, never counts as a change registering variables
- name: SGE | Check current host groups
  command: qconf -shgrpl
  ignore_errors: yes
  when: grid_engine_master == True
  register: sge_current_host_groups
  changed_when: false

- name: SGE | Build host group configuration
  template: src=ahgrp.j2 dest=/tmp/sge_ahgrp
  when: grid_engine_master == True and not '@allhosts' in sge_current_host_groups.stdout_lines

- name: SGE | Add the host group configuration
  command: qconf -Ahgrp /tmp/sge_ahgrp
  when: grid_engine_master == True and not '@allhosts' in sge_current_host_groups.stdout_lines

# Again, we don't want to do this if it already exists
- name: SGE | Check current queues
  command: qconf -sql
  ignore_errors: yes
  when: grid_engine_master == True
  register: sge_current_queues
  changed_when: false

- name: SGE | Build main queue
  template: src=aq.j2 dest=/tmp/sge_aq
  when: grid_engine_master == True and not 'main.q' in sge_current_queues.stdout_lines

- name: SGE | Add main queue
  command: qconf -Aq /tmp/sge_aq
  when: grid_engine_master == True and not 'main.q' in sge_current_queues.stdout_lines

- name: SGE | Add attribute specifications
  command: qconf -aattr {{ item.obj_spec }} {{ item.attr_name }} {{ item.val }} {{ item.obj_instance }}
  when: grid_engine_master == True
  register: sge_attribute_specifications
  changed_when: "'No modification' not in sge_attribute_specifications.stdout"
  with_items:
    - { obj_spec: 'hostgroup', attr_name: 'hostlist', val: 'master', obj_instance: '@allhosts' }
    - { obj_spec: 'queue', attr_name: 'hostlist', val: '@allhosts', obj_instance: 'main.q'}
    - { obj_spec: 'queue', attr_name: 'slots', val: '{{ ansible_processor_count }}', obj_instance: 'main.q'}
    - { obj_spec: 'hostgroup', attr_name: 'hostlist', val: 'master', obj_instance: '@allhosts' }
  

# loop through and template worker hosts
- name: SGE | Generate execution host templates
  template: src=execution_host.j2 dest=/etc/gridengine/templates/sge_execution_host_{{ item }}.sh mode=0555
  with_items: groups['worker']
  register: execution_host_template
  when: grid_engine_master == True

# loop through and setup worker hosts 
- name: SGE | Add worker hosts as execution hosts
  shell: export EDITOR=/etc/gridengine/templates/sge_execution_host_{{ item }}.sh && qconf -ae
  with_items: groups['worker']
  when: grid_engine_master == True and execution_host_template.changed
  
# template hostlist
- name: SGE | Generate hostlist
  template: src=hostlist.j2 dest=/etc/gridengine/templates/hostlist.sh mode=0555
  register: hostlist
  when: grid_engine_master == True

- name: SGE | Update hostlist
  shell: export EDITOR=/etc/gridengine/templates/hostlist.sh && qconf -ahgrp @allhosts
  when: grid_engine_master == True and hostlist.changed
  ignore_errors: yes
  
- name: SGE | Update hostlist (in a different way?)
  shell: export EDITOR=/etc/gridengine/templates/hostlist.sh && qconf -mhgrp @allhosts
  when: grid_engine_master == True and hostlist.changed
  ignore_errors: yes
  
- name: SGE | Update queue hostlist or something
  command: qconf -aattr queue hostlist @allhosts main.q
  when: grid_engine_master == True and hostlist.changed
  ignore_errors: yes

- name: SGE | Add worker queue slots
  command: qconf -aattr queue slots "[{{ item }}={{ ansible_processor_count }}]" main.q 
  with_items: groups['worker']
  when: grid_engine_master == True
  
# Setup what looks like a target load
- name: SGE | Setup target load
  command: qconf -mattr queue load_thresholds "np_load_avg={{ ansible_processor_count }}" main.q
  when: grid_engine_master == True
  
- name: SGE | Add worker consumable memory in bytes 
  command: qconf -rattr exechost complex_values h_vmem={{ ansible_memtotal_mb * 1048576  }} {{ item }}
  with_items: groups['worker']
  when: grid_engine_master == True

# setup "serial" parallel environment
- name: SGE | Template serial file
  template: src=serial_profile.j2 dest=/etc/gridengine/templates/sge_serial_profile
  register: serial_profile
  when: grid_engine_master == True
  
- name: SGE | Setup serial profile environment
  command: $item
  with_items:
      - qconf -Ap /etc/gridengine/templates/sge_serial_profile
      - qconf -aattr queue pe_list serial main.q
  when: grid_engine_master == True and serial_profile.changed

- name:  SGE | Setup worker act_qmaster line
  lineinfile: 
    line: 'master'
    dest: /var/lib/gridengine/default/common/act_qmaster
    state: present
    create: yes
  register: worker_setup
  when: grid_engine_master == False
  
- name:  SGE | Restart worker when setup changed
  service: name=gridengine-exec state=restarted
  when: worker_setup.changed
  
- name:  SGE | Ensure worker is started in general
  service: name=gridengine-exec state=started
  when: grid_engine_master == False